function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 15-Nov-2017 05:30:05

% Create figure
figure;
figure.PaperUnits = 'inches';
figure.PaperPosition = [0 0 6 3];
print('5by3DimensionsFigure','-dpng','-r0')
% Create axes
axes1 = axes;
hold(axes1,'on');

% Create plot
plot(X1,Y1,'ZDataSource','','DisplayName','data1',...
    'Color',[0 0.498039215803146 0]);

% Create ylabel
ylabel({'Y-Axis Phone Screen'},'HorizontalAlignment','center');

% Create xlabel
xlabel('X-Axis Phone Screen','HorizontalAlignment','center');

% Create title
title('Movement of Unlock Gadget','HorizontalAlignment','center',...
    'FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1080]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[900 1250]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'FontSize',18);
% Create legend
legend(axes1,'show');

