function createfigure1(X1, yvector1, X2, Y1, X3, Y2, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13, X14, X15, X16, X17, X18, X19, X20, X21, X22)
%CREATEFIGURE1(X1, yvector1, X2, Y1, X3, Y2, X4, X5, X6, X7, X8, X9, X10, X11, X12, X13, X14, X15, X16, X17, X18, X19, X20, X21, X22)
%  X1:  area x
%  YVECTOR1:  area yvector
%  X2:  vector of x data
%  Y1:  vector of y data
%  X3:  vector of x data
%  Y2:  vector of y data
%  X4:  vector of x data
%  X5:  vector of x data
%  X6:  vector of x data
%  X7:  vector of x data
%  X8:  vector of x data
%  X9:  vector of x data
%  X10:  vector of x data
%  X11:  vector of x data
%  X12:  vector of x data
%  X13:  vector of x data
%  X14:  vector of x data
%  X15:  vector of x data
%  X16:  vector of x data
%  X17:  vector of x data
%  X18:  vector of x data
%  X19:  vector of x data
%  X20:  vector of x data
%  X21:  vector of x data
%  X22:  vector of x data

%  Auto-generated by MATLAB on 15-Nov-2017 21:54:09

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Activate the left side of the axes
yyaxis(axes1,'left');
% Create area
area(X1,yvector1);

% Set the remaining axes properties
set(axes1,'YColor',[0 0 0]);
% Activate the right side of the axes
yyaxis(axes1,'right');
% Create plot
plot(X2,Y1,'LineWidth',6,'Color',[0.85 0.325 0.098]);

% Create plot
plot(X3,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X4,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X5,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X6,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X7,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X8,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X9,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X10,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X11,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X12,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X13,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X14,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X15,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X16,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X17,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X18,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X19,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X20,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X21,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Create plot
plot(X22,Y2,'Marker','*','LineStyle','none','Color',[0 1 0]);

% Set the remaining axes properties
set(axes1,'YColor',[0.85 0.325 0.098]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XTick',...
    [2279 5694 9099 12287 16165 19781 22971 26454 29866 33281]);
